<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="13491" started-at="2018-12-12T21:38:06Z" finished-at="2018-12-12T21:38:19Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="13491" started-at="2018-12-12T21:38:06Z" finished-at="2018-12-12T21:38:19Z">
      <class name="pomDesign.webOrderLoginPage">
        <test-method status="PASS" signature="ErrorMessagePOM()[pri:0, instance:pomDesign.webOrderLoginPage@380fb434]" name="ErrorMessagePOM" duration-ms="308" started-at="2018-12-12T21:38:17Z" finished-at="2018-12-12T21:38:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ErrorMessagePOM -->
        <test-method status="PASS" signature="loginUsingPOM()[pri:0, instance:pomDesign.webOrderLoginPage@380fb434]" name="loginUsingPOM" duration-ms="228" started-at="2018-12-12T21:38:18Z" finished-at="2018-12-12T21:38:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginUsingPOM -->
      </class> <!-- pomDesign.webOrderLoginPage -->
      <class name="pomDesign.AllOrdersLoginPage">
        <test-method status="PASS" signature="setUp()[pri:0, instance:pomDesign.AllOrdersLoginPage@21bcffb5]" name="setUp" is-config="true" duration-ms="5816" started-at="2018-12-12T21:38:06Z" finished-at="2018-12-12T21:38:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:pomDesign.webOrderLoginPage@380fb434]" name="setUp" is-config="true" duration-ms="4414" started-at="2018-12-12T21:38:12Z" finished-at="2018-12-12T21:38:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="ProductTest()[pri:0, instance:pomDesign.AllOrdersLoginPage@21bcffb5]" name="ProductTest" duration-ms="1365" started-at="2018-12-12T21:38:16Z" finished-at="2018-12-12T21:38:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [$1000] but found [$100]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [$1000] but found [$100]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pomDesign.AllOrdersLoginPage.ProductTest(AllOrdersLoginPage.java:92)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:282)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:83)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:114)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductTest -->
        <test-method status="PASS" signature="closeUp()[pri:0, instance:pomDesign.AllOrdersLoginPage@21bcffb5]" name="closeUp" is-config="true" duration-ms="651" started-at="2018-12-12T21:38:18Z" finished-at="2018-12-12T21:38:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeUp -->
        <test-method status="PASS" signature="closeUp()[pri:0, instance:pomDesign.webOrderLoginPage@380fb434]" name="closeUp" is-config="true" duration-ms="685" started-at="2018-12-12T21:38:19Z" finished-at="2018-12-12T21:38:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeUp -->
      </class> <!-- pomDesign.AllOrdersLoginPage -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
